# Generated by Django 4.2.7 on 2023-11-25 17:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("control_blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entrada",
            name="fecha_publicacion",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
