# Generated by Django 4.2.7 on 2023-11-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control_blog", "0005_alter_entrada_autor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entrada",
            name="autor",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="entrada",
            name="titulo",
            field=models.CharField(default="ValorPredeterminado", max_length=64),
        ),
    ]
