# Generated by Django 4.2.7 on 2023-11-26 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("control_blog", "0006_alter_entrada_autor_alter_entrada_titulo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entrada",
            name="subtitulo",
        ),
    ]
